Downstairs_group:
  name: "Downstairs"
  entities:
    - group.Kitchen_group
    - group.LR_group
    - group.DR_group

Upstairs_group:
  name: "Upstairs"
  entities:
    - group.Bedroom_group
    - group.Office_group

# Definitions for groups found in customizations.yaml
Kitchen_group:
  name: "Kitchen"
  entities:
    - light.kitchen_ceiling_lights

LR_group:
  name: "Living Room"
  entities:
    - light.lr_lamp_lights

DR_group:
  name: "Dining Room"
  entities:
    - light.dr_lamp_light

Bedroom_group:
  name: "Bedroom"
  entities:
    - light.philips_lst002_3e53a003_level_light_color_on_off
    - switch.sonoff_s31_lite_zb_0f636a22_on_off
    - switch.sonoff_s31_lite_zb_4b7e6a22_on_off

Office_group:
  name: "Office"
  entities:
      - light.philips_lct016_5244f203_level_light_color_on_off