# Definitions for groups of individual light entities (i.e. 
# group of recessed bulbs in the kitchen, as defined in config)
- platform: group
  name: LR Lamp Lights
  entities:
  - light.soft_white_hue_5_level_on_off
  - light.soft_white_hue_6_level_on_off
  - light.soft_white_hue_7_level_on_off

- platform: group
  name: DR Lamp Light
  entities:
  - light.soft_white_hue_8_level_on_off